# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - mcp-func-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # デプロイに使用する ZIP ファイル名（ルートに host.json / requirements.txt を含む形式で生成）
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'release.zip'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # （任意）テストを追加したい場合は、この前に setup-python / pip install を追加してください。

      - name: Create deployment zip (functions-py contents as root)
        run: |
          (cd functions-py && zip -r ../release.zip .)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ABC3F4327F4D447AA50F453B92854231 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7B5AF70BDAAC439DA1490C0EAAF4B3A5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_349001CDCCEE446A829215DE87733371 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'mcp-func-test'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}