# Azure Functions デプロイ用 GitHub Action のドキュメント: https://github.com/azure/functions-action
# Azure 向けの他の GitHub Actions: https://github.com/Azure/actions
# Python / GitHub Actions / Azure Functions に関する詳細: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - func-mcp-poc-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # functions-py ディレクトリをそのままデプロイ (host.json が直下になる)
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions-py'
  PYTHON_VERSION: '3.12' # 使用する Python バージョン (3.6, 3.7, 3.8 をサポートと記載)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # actions/checkout に必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies (functions-py)
        run: pip install -r functions-py/requirements.txt

      # 任意: ここでテスト実行ステップを追加できます

      - name: Zip artifact for deployment (functions-py only, exclude emulator data & local settings)
        run: |
          zip -r release.zip functions-py \
            -x 'functions-py/__azurite_db_*' \
            -x 'functions-py/__blobstorage__/*' \
            -x 'functions-py/__queuestorage__/*' \
            -x 'functions-py/local.settings.json'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # JWT (OIDC トークン) 要求に必要
      contents: read # actions/checkout に必要

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E537B1FA30D840FC876370051A2A4645 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BFFF842DD6B6444398BDE796E3F4D29F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2AC6414730BF4446B55060F6180028E4 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'func-mcp-poc-001'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
